apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: met-image-search-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: met-image-search-server
    spec:
      containers:
      - name:  met-image-search-container
        image: mhamilton723/met-image-search:0.2
        ports:
        - containerPort: 5000
        resources:
          limits:
            nvidia.com/gpu: 1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run:  met-image-search-service
  name:  met-image-search-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app:  met-image-search-server
  type: LoadBalancer
